<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210830050254 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE actividad_proceso DROP FOREIGN KEY FK_RELATIONSHIP_5');
        $this->addSql('ALTER TABLE funcionarios_tramite DROP FOREIGN KEY FK_RELATIONSHIP_13');
        $this->addSql('ALTER TABLE funcionarios_tramite DROP FOREIGN KEY FK_RELATIONSHIP_16');
        $this->addSql('ALTER TABLE actividad_proceso DROP FOREIGN KEY FK_RELATIONSHIP_10');
        $this->addSql('ALTER TABLE proceso_tramite DROP FOREIGN KEY FK_RELATIONSHIP_3');
        $this->addSql('ALTER TABLE tramite DROP FOREIGN KEY FK_RELATIONSHIP_2');
        $this->addSql('ALTER TABLE cliente_tramite DROP FOREIGN KEY FK_RELATIONSHIP_12');
        $this->addSql('ALTER TABLE proceso_tramite DROP FOREIGN KEY FK_RELATIONSHIP_4');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nombre VARCHAR(50) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('DROP TABLE actividad');
        $this->addSql('DROP TABLE actividad_proceso');
        $this->addSql('DROP TABLE cliente_tramite');
        $this->addSql('DROP TABLE funcionarios_tramite');
        $this->addSql('DROP TABLE proceso');
        $this->addSql('DROP TABLE proceso_tramite');
        $this->addSql('DROP TABLE tipo_tramite');
        $this->addSql('DROP TABLE tramite');
        $this->addSql('ALTER TABLE cliente DROP FOREIGN KEY FK_RELATIONSHIP_17');
        $this->addSql('DROP INDEX CEDULA ON cliente');
        $this->addSql('DROP INDEX MOVIL ON cliente');
        $this->addSql('DROP INDEX FK_RELATIONSHIP_17 ON cliente');
        $this->addSql('ALTER TABLE cliente DROP ID_FUNC, CHANGE CEDULA CEDULA INT NOT NULL, CHANGE NOMBRE NOMBRE VARCHAR(255) NOT NULL, CHANGE APELLIDO APELLIDO VARCHAR(255) NOT NULL, CHANGE ESTADO_CIVIL ESTADO_CIVIL VARCHAR(255) NOT NULL, CHANGE DIRECCION DIRECCION VARCHAR(255) NOT NULL, CHANGE TELEFONO TELEFONO INT NOT NULL, CHANGE MOVIL MOVIL INT NOT NULL, CHANGE EMAIL EMAIL VARCHAR(255) NOT NULL');
        $this->addSql('DROP INDEX CEDULA_FUN ON funcionario');
        $this->addSql('DROP INDEX EMAIL ON funcionario');
        $this->addSql('ALTER TABLE funcionario DROP PASSWORD, CHANGE ID_ROL ID_ROL INT DEFAULT NULL, CHANGE CEDULA_FUN CEDULA_FUN INT NOT NULL, CHANGE NOMBRE NOMBRE VARCHAR(255) NOT NULL, CHANGE APELLIDO APELLIDO VARCHAR(255) NOT NULL, CHANGE EMAIL EMAIL VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE funcionario RENAME INDEX fk_relationship_14 TO IDX_7510A3CFC03BBFD5');
        $this->addSql('ALTER TABLE rol CHANGE ROL ROL VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE actividad (ID_CAMPO INT AUTO_INCREMENT NOT NULL, CAMPO VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, PRIMARY KEY(ID_CAMPO)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE actividad_proceso (ID_CAMPO INT DEFAULT NULL, ID_PROCESO INT DEFAULT NULL, ID_CAMPO_PROCESO INT AUTO_INCREMENT NOT NULL, INDEX FK_RELATIONSHIP_10 (ID_PROCESO), INDEX FK_RELATIONSHIP_5 (ID_CAMPO), PRIMARY KEY(ID_CAMPO_PROCESO)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE cliente_tramite (ID_CLIENTETRAMITE INT AUTO_INCREMENT NOT NULL, ID_TRAMITE INT DEFAULT NULL, ID_CLIENTE INT DEFAULT NULL, FUNCIONARIO VARCHAR(50) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_spanish2_ci`, INDEX FK_RELATIONSHIP_11 (ID_CLIENTE), INDEX FK_RELATIONSHIP_12 (ID_TRAMITE), PRIMARY KEY(ID_CLIENTETRAMITE)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE funcionarios_tramite (ID_CAMPO_PROCESO INT DEFAULT NULL, ID_CLIENTETRAMITE INT DEFAULT NULL, ID_FUNC INT DEFAULT NULL, DATO VARCHAR(50) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_spanish2_ci`, INDEX FK_RELATIONSHIP_15 (ID_FUNC), INDEX FK_RELATIONSHIP_16 (ID_CLIENTETRAMITE), INDEX FK_RELATIONSHIP_13 (ID_CAMPO_PROCESO)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE proceso (ID_PROCESO INT AUTO_INCREMENT NOT NULL, NOMBRE_PROCESO VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, DETALLE VARCHAR(400) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_spanish2_ci`, PRIMARY KEY(ID_PROCESO)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE proceso_tramite (ID_PROCESO INT DEFAULT NULL, ID_TRAMITE INT DEFAULT NULL, ID_PROCESOTRAMITE INT AUTO_INCREMENT NOT NULL, INDEX FK_RELATIONSHIP_3 (ID_PROCESO), INDEX FK_RELATIONSHIP_4 (ID_TRAMITE), PRIMARY KEY(ID_PROCESOTRAMITE)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tipo_tramite (ID_TIPO INT AUTO_INCREMENT NOT NULL, NOMBRE_TIPO VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, PRIMARY KEY(ID_TIPO)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tramite (ID_TRAMITE INT AUTO_INCREMENT NOT NULL, ID_TIPO INT DEFAULT NULL, TRAMITE VARCHAR(80) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, INDEX FK_RELATIONSHIP_2 (ID_TIPO), PRIMARY KEY(ID_TRAMITE)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE actividad_proceso ADD CONSTRAINT FK_RELATIONSHIP_10 FOREIGN KEY (ID_PROCESO) REFERENCES proceso (ID_PROCESO)');
        $this->addSql('ALTER TABLE actividad_proceso ADD CONSTRAINT FK_RELATIONSHIP_5 FOREIGN KEY (ID_CAMPO) REFERENCES actividad (ID_CAMPO)');
        $this->addSql('ALTER TABLE cliente_tramite ADD CONSTRAINT FK_RELATIONSHIP_11 FOREIGN KEY (ID_CLIENTE) REFERENCES cliente (ID_CLIENTE)');
        $this->addSql('ALTER TABLE cliente_tramite ADD CONSTRAINT FK_RELATIONSHIP_12 FOREIGN KEY (ID_TRAMITE) REFERENCES tramite (ID_TRAMITE)');
        $this->addSql('ALTER TABLE funcionarios_tramite ADD CONSTRAINT FK_RELATIONSHIP_13 FOREIGN KEY (ID_CAMPO_PROCESO) REFERENCES actividad_proceso (ID_CAMPO_PROCESO)');
        $this->addSql('ALTER TABLE funcionarios_tramite ADD CONSTRAINT FK_RELATIONSHIP_15 FOREIGN KEY (ID_FUNC) REFERENCES funcionario (ID_FUNC)');
        $this->addSql('ALTER TABLE funcionarios_tramite ADD CONSTRAINT FK_RELATIONSHIP_16 FOREIGN KEY (ID_CLIENTETRAMITE) REFERENCES cliente_tramite (ID_CLIENTETRAMITE)');
        $this->addSql('ALTER TABLE proceso_tramite ADD CONSTRAINT FK_RELATIONSHIP_3 FOREIGN KEY (ID_PROCESO) REFERENCES proceso (ID_PROCESO)');
        $this->addSql('ALTER TABLE proceso_tramite ADD CONSTRAINT FK_RELATIONSHIP_4 FOREIGN KEY (ID_TRAMITE) REFERENCES tramite (ID_TRAMITE)');
        $this->addSql('ALTER TABLE tramite ADD CONSTRAINT FK_RELATIONSHIP_2 FOREIGN KEY (ID_TIPO) REFERENCES tipo_tramite (ID_TIPO)');
        $this->addSql('DROP TABLE user');
        $this->addSql('ALTER TABLE cliente ADD ID_FUNC INT DEFAULT NULL, CHANGE CEDULA CEDULA NUMERIC(10, 0) NOT NULL, CHANGE NOMBRE NOMBRE VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, CHANGE APELLIDO APELLIDO VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, CHANGE ESTADO_CIVIL ESTADO_CIVIL VARCHAR(12) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, CHANGE DIRECCION DIRECCION VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, CHANGE TELEFONO TELEFONO NUMERIC(10, 0) NOT NULL, CHANGE MOVIL MOVIL NUMERIC(10, 0) NOT NULL, CHANGE EMAIL EMAIL VARCHAR(80) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`');
        $this->addSql('ALTER TABLE cliente ADD CONSTRAINT FK_RELATIONSHIP_17 FOREIGN KEY (ID_FUNC) REFERENCES funcionario (ID_FUNC)');
        $this->addSql('CREATE UNIQUE INDEX CEDULA ON cliente (CEDULA)');
        $this->addSql('CREATE UNIQUE INDEX MOVIL ON cliente (MOVIL)');
        $this->addSql('CREATE INDEX FK_RELATIONSHIP_17 ON cliente (ID_FUNC)');
        $this->addSql('ALTER TABLE funcionario ADD PASSWORD VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, CHANGE CEDULA_FUN CEDULA_FUN NUMERIC(10, 0) NOT NULL, CHANGE NOMBRE NOMBRE VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, CHANGE APELLIDO APELLIDO VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, CHANGE EMAIL EMAIL VARCHAR(80) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`, CHANGE ID_ROL ID_ROL INT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX CEDULA_FUN ON funcionario (CEDULA_FUN)');
        $this->addSql('CREATE UNIQUE INDEX EMAIL ON funcionario (EMAIL)');
        $this->addSql('ALTER TABLE funcionario RENAME INDEX idx_7510a3cfc03bbfd5 TO FK_RELATIONSHIP_14');
        $this->addSql('ALTER TABLE rol CHANGE ROL ROL VARCHAR(25) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish2_ci`');
    }
}
